### ISSUE TITLE
Autorisation not working any more?

### ISSUE THREAD

**Issue by Denn2705** [psauliere/netatmo#1]
Hi, i set up my Raspberry exactly like in the manuall (only with bigger Waveshare Display.

But i always get the Error:
```
pi@raspberrypi:~/netatmo $ ./netatmo.py
netatmo.py v0.18 2021-01-10
2024-06-16 19:19:25,147 | authenticate() HTTPError
2024-06-16 19:19:25,150 | 400 {"error":"unauthorized_client"}
2024-06-16 19:19:25,150 | authenticate() exiting
Traceback (most recent call last):
  File "/home/pi/netatmo/./netatmo.py", line 217, in <module>
    main()
  File "/home/pi/netatmo/./netatmo.py", line 201, in main
    get_station_data()
  File "/home/pi/netatmo/./netatmo.py", line 108, in get_station_data
    'access_token': g_token['access_token'],
KeyError: 'access_token'
```

Is there something changed in the way how to authenticate at Netatmo?

My Username, Passwort, Client_ID, Client_Secret and device ID are correct in the config.json file.

Thanks in advance!

BR
Dennis

**Comment by psauliere** [comment]
Hi Dennis,

The [client credentials grant type](https://dev.netatmo.com/apidocumentation/oauth#client-credential) still works, but under the condition that the app (client id + client secret) must have been created by the user (user name + password) specified in the request.

The error code means "The client is not authorized to use the requested response type." So I would double check the config file, username/password and client_id/client_secret (https://dev.netatmo.com/apps/).

Let me know and I will do some new tests as soon as possible.
Thank you.

**Comment by psauliere** [comment]
Update: I got the same error in a quick test with a new app. I will have to investigate a bit later.

**Comment by psauliere** [comment]
Well the authentication doesn't work but the token refresh still works as expected. The cool thing is that you can generate a new token on the dev site, https://dev.netatmo.com/apps/

So here is a quick and dirty workaround:

- copy the sample_token.json file to a new token.json file
- go to https://dev.netatmo.com/apps/, authenticate if necessary, and select your app.
- under "Token generator", select the "read_station" scope and click on "Generate Token".
- it takes a while, but you will get a page where you have to authorize your app to access to your data. Click on "Yes I accept".
- you now have a new Access Token and a new Refresh token.
- click on the access token, it will copy it on your clipboard. Paste it in your token.json file in place of the token placeholder.
- same thing for the refresh token.
- save the token.json file

In my case the netatmo.py script works fine after that. If it works, wait ~10 minutes to see if the token refresh works.

As for the cause of the problem, I don't know yet.

Let me know if the workaround works.

**Comment by Denn2705** [comment]
Thanks for your investigation! The Workaround worked so far :)

`2024-06-18 16:39:15,934 | Time 16:39 | Pressure 1009.6 | Indoor 25.7 | Outdoor 30.4 `

So Data is transmitted fine right now👍 

Is there a time when the workaround token are getting invalid? I read something about 3hours?

**Comment by psauliere** [comment]
OK Everyone has this same error because Netatmo removed the Client Credentials grant type. This means I will have to turn this workaround into plain documentation: for the first access+refresh tokens, use the dev site.

As for the token refresh, don't worry, the script manages it whenever the token expires.

Thank you for reminding me to update my little project!

**Comment by psauliere** [comment]
Change in the code and in the documentation are done.
